/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/hamburger.glb 
Author: simalmaii (https://sketchfab.com/simalmaii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hamburger-346ebe0033ba48f7bc2e10d44a5b482f
Title: Hamburger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';

export default function Burger(props) {

  const groupRef = useRef();
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Adjust the speed of rotation as needed
    }
  });

  const { nodes, materials } = useGLTF('/hamburger.glb')
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/hamburger.glb')
